### ISSUE TITLE
Read HTML contents from file.

### ISSUE THREAD

**Issue by fabulousduck** [tsoding/website-in-assembler#18]
In the current code, the HTML part of the site is hardcoded into the [main.asm](https://github.com/tsoding/wassm/blob/master/src/main.asm) file.

This is rather ugly and could be solved in not too many lines of code if needed moved to its own `.asm` file for the sake of keeping the code clean.

If i find some time today or this week, I will see about making a pr for this issue.

**Comment by rexim** [comment]
@fabulousduck thanks for filing an issue! Makes sense. :)

**Comment by fabulousduck** [comment]
I have to put making this PR on hold until i fix #32 since i need that to start working on this one

**Comment by rexim** [comment]
@fabulousduck sorry, but I'm taking that to implement on the stream :D
